### PR TITLE
Use cryptohash-sha1 instead of the deprecated cryptohash

### LINKED ISSUE #52: Cryptohash is deprecated in favor of cryptonite
> DEPRECATED: this library is still fully functional, but please use cryptonite for new projects and convert old one to use cryptonite. This is where things are at nowadays.

### PR DESCRIPTION
**Pull request by amesgen**
also drops several transitive dependencies like cryptonite, memory and basement

Closes #52

### CODE REVIEW

**Comment by amesgen** [comment]
The CI failures look unrelated FTR, but maybe it is as easy as regenerating the Haskell-CI config, should I do that in this PR?

**Comment by mgsloan** [comment]
Sure, regenerated CI config would be appreciated, thanks!

**Comment by amesgen** [comment]
Pushed, CI should work now:

 - Dropped GHC <8.4 as `th-utilities` does not compile there due to https://github.com/fpco/th-utilities/pull/16.
 - Added GHC 9.2 and 9.4; Cabal does not find a plan for 9.6 yet due to https://github.com/fpco/weigh/issues/49.
 - Update hlint to 3.5.
 - Fixed a compilation failure with `time >= 1.11`; #164 only fixed the library part.

**Comment by amesgen** [comment]
Anything I can do to move this forward?

**Comment by mgsloan** [comment]
Argh, sorry for the huge delay!  Somehow got buried in my email.

Thanks for all the fixes!

**Comment by mgsloan** [comment]
Fixes included in store-0.7.18, store-core-0.4.4.6, store-streaming-0.2.0.5

**Pull request merged**
