### PR TITLE
Remove fail from dependencies

### PR DESCRIPTION
**Pull request by felixonmars**
It's already in the conditional dependencies.

### CODE REVIEW

**Comment by mgsloan** [comment]
Good catch, thanks!

**Comment by mgsloan** [comment]
Released in version `0.7.5`

**Comment by felixonmars** [comment]
@mgsloan It seems I changed `store-core` but you released an unchanged `store` ._.

**Comment by mgsloan** [comment]
Ah good point!  I have released new versions after merging your other PR

**Comment by felixonmars** [comment]
@mgsloan It works fine now. Thanks!

**Pull request merged**
